### ISSUE TITLE
Offline-first docs

### ISSUE THREAD

**Issue by ai** [logux/docs#44]
We need a doc of using `IndexedDB`

**Comment by uncaught** [comment]
Oh, wonderful, I was just about to open an issue with a similar topic!

I have this classic offline/optimistic-ui situation:
1. Create an object A (with client-generated id, lets say `123`)
2. Dispatch the create-action for A
3. The reducer (client) will immediately add A to the redux-store
4. The client will immediately display a component X with details on A
5. This component X creates a subscription for A (e.g. `{channel: 'object/123'}`)
6. The subscription runs into `Access denied` because the server did not yet process the create-action and does not know that `123` belongs to the current user.

This is not a bug, it's an implementation detail of working with an optimistic ui and timing.

There are several solutions I came up with so far:
1. `await` the create-action - which will work, but will turn your ui pessimistic and remove offline-capability.
2. Grant access on unknown ids. In this case, allow channel-access to `object/123` because `123` is not known at all. The server will then either skip the `sendBack` entirely or send something like `null`.
3. Prevent the subscription until the create-action has succeeded. This would require A to have a flag like `new: true` and the component X would only subscribe to the channel if there is no such flag. The server would need to `sendBack` an action to the client which will remove the flag after the server has processed the create-action for A. 
    1. This also requires the server to modify the dispatched action (remove flag) before the `resend` - I don't know if that's possible.
    2. Or keep the information that A is new outside the action/store, which would make this impure.

**Comment by ai** [comment]
Great use case! Yeap, we need some warning in the docs about this case.

**Comment by ai** [comment]
Duplicate https://github.com/logux/logux/issues/9
